### ISSUE TITLE
Modulefile for gcc-toolchain broken

### ISSUE THREAD

**Issue by sawenzel** [alisw/alidist#1122]
Running on the cvmfs release (alice-nightlies.cern.ch) (CentOS-7):

```
module load GCC-Toolchain/v6.2.0-alice1-4 
```
(same as alienv enter GCC-Toolchain/v6.2.0-alice1-4)

yields an error message:

```
GCC-Toolchain/v6.2.0-alice1-4(52):ERROR:105: Unable to locate a modulefile for 'Toolchain/GCC-v6.2.0'
```

Somehow this modulefile depends on another non-existing modulefile Toolchain/GCC-v6.2.0. The actual compiler is loaded and works. However, this error prevents a correct working of the module file (for instance when unloading). Probably we should just remove dependency on Toolchain/GCC-v6.2.0 which seems to be not needed.

**Comment by dberzano** [comment]
@ktf is right. The error comes from the fact that we need to try to load a module before determining it did not exist (we cannot check in advance with modules, unfortunately). On the local `alienv` we filter the message out. I am afraid that this utter complication is needed in order to keep it compatible with the Grid. That said, `alienv` (local or from CVMFS) is _the_ way to load our modules, not `module load` (there are some slight but notable differences in the way we set the environment).
