### ISSUE TITLE
FairMQ detection mechanism

### ISSUE THREAD

**Issue by ktf** [alisw/alidist#1243]
@dberzano I guess I am missing something but how can the FairRoot recipe pick up FairMQ, given there is no "-DFAIRMQ_DIR" or similar?

**Comment by dberzano** [comment]
Hmm I believe environment variables are used. The transition was handled by @dennisklein, let's see if he has more information. I agree it would be better _not_ to use environment variables by the way.

**Comment by dennisklein** [comment]
CMake automatically looks up the environment with `find_package`, see [CMP0074](https://cmake.org/cmake/help/v3.12/policy/CMP0074.html). But this cannot be the reason why FairMQ is found, because

1. we use older CMake in `--defaults o2` (even though the CMP0074 behaviour was first introduced in 3.9.1, but apparently it was removed again shortly after 3.9.1 until 3.12.0, which I did not know) and
2. env variables are case sensitive (so the env var `FAIRMQ_ROOT` from alibuild also has no effect, I verified)

The real reason why it is still found, is because of the `PATH` variable, which contains something like `.../sw/fedora28_x86-64/FairMQ/v1.2.3-1/bin`, read lookup rule 4 [here](https://cmake.org/cmake/help/v3.11/command/find_package.html).

Summary: Because lookup worked when I proposed the transition changes with splitted FairMQ repo and I knew about the `{Package}_ROOT` lookup rule of `find_package` in 3.9.1, I assumed it worked in-casesensitiv and still worked in 3.11. Both wrong^^

I will fix it with the CMake modernization probably in September. The intended behaviour from our side is, that `FAIRMQ_ROOT` as CMake var and env var will be used as hints for the lookup which is currently not the case.

Alternatively, you can use
* CMake var `CMAKE_PREFIX_PATH`
* CMake and env var `FairMQ_ROOT` in 3.9.1 and 3.12+
* env var `PATH` (`/bin` and `/sbin` are automatically stripped)
* CMake var `FairMQ_DIR` pointing to the exact subdir containing `FairMQConfig.cmake`
