### ISSUE TITLE
Python-modules compilation fails on CC7

### ISSUE THREAD

**Issue by awegrzyn** [alisw/alidist#1932]
```
 gcc: skgarden/mondrian/tree/_tree.c
    skgarden/mondrian/tree/_tree.c:29:10: fatal error: Python.h: No such file or directory
     #include "Python.h"
              ^~~~~~~~~~
    compilation terminated.
```

**Comment by sy-c** [comment]
Not related to the same cause, I also had problems in aliBuild for python-modules to compile.

/v1-11/lib: PYTHONHOME=/home/sylvain/alibuild_test/sw/INSTALLROOT/9d6a605324a981c4b60b429d5551b387660ec14b/slc7_x86-64/Python/v3.6.8-1 python3 -c 'import _tkinter'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named '_tkinter'

I managed to fix it by installing tk-devel RPM.
Maybe this should be added to the "system dependencies" checks ?

**Comment by ktf** [comment]
The prerequisites are listed in:

https://alice-doc.github.io/alice-analysis-tutorial/building/prereq-centos7.html

which is obviously too verbose, but it does list `tk-devel`.

That said I am trying to put together a meta-RPM at:

https://github.com/alisw/alice-system-deps

which should simplify things, but I am fighting with some authentication issues when trying to publish from Travis. I will keep you posted.

**Comment by sy-c** [comment]
Such meta-rpm would be nice indeed!

Independently of these good instructions (which have unfortunately changed since last time I copied them to my setup script, missing this last tk-devel item), I would expect that alibuild checks all system dependencies and report which are not satisfied before starting to compile anything, to avoid potentially obscure error messages later. I had the impression it was the case for some of the packages... shouldn't it be done exhaustively ?

BTW, in the prerequisites, it is missing gcc-g++ (cf O2-490)

**Comment by ktf** [comment]
yes, we could introduce a system check of tkinter. as well.

**Comment by ktf** [comment]
For the record, the metaRPM actually exists now. I am closing this.
