### ISSUE TITLE
FairMQ fails to build with system flatbuffers, if system flatbuffers were not compiled with -fPIC

### ISSUE THREAD

**Issue by davidrohr** [alisw/alidist#3164]
This problem appears for me in a CentOS8 container, when installing the system package for flatbuffers.
It is picker up, but it is not compatible to FairMQ after some recent changes, since it was not compiled with -fPIC.
I think this is related to the recent fix for FairMQ, so it is actually intended. Probably we need to add a check in the prefer-system-check of flatbuffers that it was build with -fPIC?
Ping @rbx @ktf

**Comment by ktf** [comment]
Is flatbuffers in fairmq used for anything critical? I am not sure there is any simple way to detect -fPIC...

**Comment by ktf** [comment]
In any case we would have the same problem with arrow, actually... Given flatbuffers is small, I would simply compile our own copy always...

**Comment by rbx** [comment]
flatbuffers is used for the SDK Commands that fly between ODC and DDS plugin.
We are in the process of moving SDK code to the ODC repository. As ODC already uses protobuf for other stuff, we will likely change the commands implementation to use protobuf instead of flatbuffers. But this is very low priority, as it currently works fine as it is.

**Comment by ktf** [comment]
I actually like flatbuffers more than protobuf. That said, let's just always pick it up from the system.

**Comment by davidrohr** [comment]
PR #3165
