### ISSUE TITLE
Gracefully handle root6

### ISSUE THREAD

**Issue by Barthelemy** [alisw/alidist#337]
We need a recipe for it to be used by O2.

**Comment by ktf** [comment]
The recipe itself is in the IB/master/root6 branch, which should be updated automatically from the `IB/v5-08/prod` branch. Unless I am mistaking, we cannot simply have a root6 recipe, because part of alidist which depend on root (most notably `AliRoot` and `GEANT_VMC` :) ) are shared by O2 and AliPhysics, and that would create a mess. I propose we do the following:

- [ ] Rebase the `IB/master/root6` branch on `IB/v5-08/next`, so that we ROOT6 builds track a more dynamic environment.
- [ ] Start to track O2 only externals in that branch.

**Comment by Barthelemy** [comment]
ok I agree with what you say. 
what about having a branch for O2 based on next instead of using root6 ?

**Comment by ktf** [comment]
"next" is what we use for AliRoot things which end up in production, so the root there is 5.34.00 because eventually it gets merged in prod.

**Comment by ktf** [comment]
I.e. every month or so we do the the merge.

**Comment by Barthelemy** [comment]
Coming back to this, I am still wondering why we don't have a dedicated branch for O2 that would be rebased on branch IB/v5-08/next for the time being, the same way root6 branch is.

**Comment by ktf** [comment]
Ok, I've created the branch for you and it tracks root6.
