### ISSUE TITLE
AliRoot dependency for O2

### ISSUE THREAD

**Issue by Barthelemy** [alisw/alidist#408]
We should use a tag or at least a commit because using simply master means that every time I call alibuild it rebuilds AliRoot as someone has made a commit.

**Comment by ktf** [comment]
This is deliberate because we want to make sure people use the latest AliRoot when they develop, at least at this point. If they want to fix a tag they are told to do:

```
alibuild init AliRoot@v5-08-10,AliPhysics@master
```

which effectively fixes your development packages to a given tag. We can of course change this, but then it means we must be extremely proactive at changing the tag in the recipe when we have a release.

**Comment by ktf** [comment]
Can we close this?

**Comment by Barthelemy** [comment]
yes. By the way, I think that this is why I had several "development" packages and no more space on the disk. I used init to fix the tag.

Basically every time we use alibuild for O2 we get to recompile aliroot or we get to have it as a development package ?

**Comment by ktf** [comment]
No, we should fix the aliroot version in the recipe and override it in the daily builds, I guess. I will open a separate ticket.
