### ISSUE TITLE
ROOT does not compile with python error

### ISSUE THREAD

**Issue by rqwa** [alisw/alidist#431]
Hello @dberzano, the problem still exists:
```
aliBuild init AliRoot,AliPhysics --dist IB/v5-08/next -z ali-master
aliBuild -z -w ../sw build AliPhysics --jobs 24 --dist IB/v5-08/next --disable fastjet 2>&1 | tee build.log.txt
```
Results in the same crash when compiling ROOT. See attached logs.

[alidoctor.log.txt](https://github.com/alisw/alidist/files/308544/alidoctor.log.txt)
[build.log.txt](https://github.com/alisw/alidist/files/308545/build.log.txt)
[ROOT.log.txt](https://github.com/alisw/alidist/files/308546/ROOT.log.txt)

**Comment by ktf** [comment]
The problem is that your custom installation of python in `/cm/shared/apps/python/2.7.8/lib/` is broken, due to the fact libpython2.7.a  was compiled without `-fPIC`:

```
[ 69%] /data02/aliceexp/marquard/software/alibuild_test/alibuild13/sw/slc6_x86-64/GCC-Toolchain/v4.9.3-1/bin/../lib/gcc/x86_64-unknown-linux-gnu/4.9.3/../../../../x86_64-unknown-linux-gnu/bin/ld: /cm/shared/apps/python/2.7.8/lib/libpython2.7.a(myreadline.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/cm/shared/apps/python/2.7.8/lib/libpython2.7.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
```

I personally think this is an issue with the root `CMakeLists.txt`, since it should have detected this and disabled PyROOT, IMHO. The workarounds I can think of are:

- Correctly pass compilation options to your custom python to use `-fPIC` or uninstall it / put it outside the path.
- Disable PyROOT explicitly in `alidist/root.sh`(I think with `-DPYTHON=OFF`, but I could be wrong).

**Comment by rqwa** [comment]
Thanks @ktf and @dberzano , for your help.
With `--enable-shared` as option for compiling python the `-fPIC`  flag is set and at least the compilation at Fedora 23 works. Is misunderstood the error message and thought that the flag has to be set in the ROOT configure.
