### ISSUE TITLE
AliRoot local mode

### ISSUE THREAD

**Issue by emmadapo** [alisw/alidist#657]
Hi,
I use for the first time AliRoot and I'm trying to run a simple test with my
notebook (runtest.sh in ppbench). Unfortunately I got several error
messages (see attachment).  Can anybody help me?
Note: the AliRoot installation and compilation was OK, apparently.
Thanks in advance
 
[AliRootLog.txt](https://github.com/alisw/alidist/files/857663/AliRootLog.txt)

**Comment by aaniin** [comment]
Hello @emmadapo ,

Can you please close this issue?
It is fixed with Rubens commit today here https://github.com/alisw/AliRoot/pull/272 
I tested it, and can easily run the ppbench by following the procedure linked by Ruben: http://alisw.github.io/git-advanced/#use-the-reference-ocdb
I.e.
aliBuild build AliPhysics
aliBuild build AliRoot-OCDB
alienv enter AliPhysics/latest AliRoot-OCDB/latest
cd $ALICE_ROOT/test/ppbench
./runtest.sh 

Cheers,
Hans

**Comment by ktf** [comment]
I assume this is fixed (and not related to alidist). Please reopen if not the case.
