### ISSUE TITLE
When building LHAPDF on slc7 configure complains about wrong option

### ISSUE THREAD

**Issue by ktf** [alisw/alidist#69]
@qgp after your changes I see:

```
DEBUG:AliRoot:b4ed0c1a: configure: WARNING: unrecognized options: --with-yaml-cpp
```

when compiling LHAPDF. Are you sure this is actually working correctly?

**Comment by qgp** [comment]
@ktf: The dependency on yaml-cpp and the config option should simply go away with the latest versions of yaml-cpp, see https://lhapdf.hepforge.org/install.html#externals. It's needed for older versions of lhapdf (I think < 6.1) for which also the config option is understood then. I don't know if you want to be able to support older versions of lhapdf, otherwise it would be as simple as removing both the dependency and the config option. Let me know if you want me to do this.

Cheers,
   Jochen

**Comment by ktf** [comment]
Can you add a case statement to add the option only in the case we are using an old version of LHAPDF?

Something like:

```
case $LHAPDF_VERSION in
  6.0*) $WITH_YAML_CPP="--with-yaml-cpp=$YAML_CPP_ROOT"
esac

...
./configure $WITH_YAML_CPP
```

should work, I guess.

**Comment by qgp** [comment]
This does not handle the dependency. IMHO, it would be more correct to pull in yaml-cpp as dependency only if it's required, i.e. version < 6.1, and then use $YAML_CPP_ROOT to decide on whether to pass this to configure. But I have not found how to specify a conditional on a version for a dependency (in the way it can be done for arch). Did I overlook something?

**Comment by ktf** [comment]
There is not such a thing for now, but we can add it to the backlog of things to do. Please open an issue and I'll look at it when I've a bit of time. For the moment I would just do the minimal change, keep the dependency and only use it when it does not complain.

**Comment by qgp** [comment]
Ok, will do as you say and make a pull request after testing.

**Comment by qgp** [comment]
Sorry, I got stuck with testing while being in Russia. Now back at CERN, and the pull request #79 is done. For reference, what works is:
```
case $PKGVERSION in
     v6.0*) WITH_YAML_CPP="--with-yaml-cpp=${YAML_CPP_ROOT}"
esac
```

**Comment by qgp** [comment]
I guess this can be closed now, right?
