### ISSUE TITLE
ROOT is rebuilt from scratch at every retry

### ISSUE THREAD

**Issue by Barthelemy** [alisw/alidist#723]
AliBuild can't build ROOT (see other ticket). Every time I retry it starts from scratch meaning that it takes ages just to try a small change. It should continue from where it failed last time.

**Comment by ktf** [comment]
This is deliberate. We allow for incremental builds only if a complete build is successful, first. This is because if that's not the case, there is a chance that a build will not be able to complete due to leftovers from the previous broken build. We can try to improve there, but it's not as easy as "just rebuild".

**Comment by Barthelemy** [comment]
I see, it makes sense. What could help is if I could load the build environment and cd to the build directory.

**Comment by ktf** [comment]
That you should be able to do by going to:

```
sw/BUILD/ROOT-latest/ROOT
```

and typing `make -j 20`. In principle our recipe should always leave a working build setup after the `./configure` / `cmake` part is done. Is that not the case?

**Comment by Barthelemy** [comment]
Ok, that is good. I can proceed like that. Thank you !
