### ISSUE TITLE
Package python 2.7

### ISSUE THREAD

**Issue by qgp** [alisw/alidist#80]
Python 2.4 or newer is required for YODA -> Rivet -> ThePEG (and other generators depending on Rivet). It is not available on SLC 5 and the lack of it is blocking the rebuild of Rivet. According to @ktf, it should be packaged.

**Comment by dberzano** [comment]
@qgp, if you have no objections I'd go for Python 2.7. OK?

**Comment by qgp** [comment]
@dberzano: Sure, if you get this compiled on SLC 5 even better.

**Comment by dberzano** [comment]
So actually Python 2.5 or greater is required for YODA. I have managed to successfully compile Python 2.7, with two modules required by YODA: numpy (easy-peasy to install) and matplotlib. The latter, unfortunately, brings two additional dependencies to the system: FreeType and libpng.

I did not make any pull request yet because we have to tell other pieces of software (expecially ROOT) to use FreeType and libpng from our recipes.

This is just to say that we are on it even if it is quite convoluted :-)
