### ISSUE TITLE
GCC / boost version

### ISSUE THREAD

**Issue by davidrohr** [alisw/alidist#876]
Hi,

the recipes defaults-o2, defaults-o2-daq, and gcc-toolchain impose minimal and maximum versions for boost and GCC. This is a bit annoying when you have an up to date linux installation.

Currently, I locally have to modify all the recipes and remove maximum version limits, and yet I have not seen any problems.
Could we perhaps introduce an experimental or unstable environment variable, or any other means, which would disable all the checks for a maximum version?
(We could leave those checks in, where we know that a new version is buggy, and then throw a detailed error like 'GCC > 6.2 leads to miscompilation with O2 package'.)

But that would enable people to use an up to date system in a general and clean way.

Cheers
David

**Comment by ktf** [comment]
PRs to improve the detection / messages are of course welcome. ;-) For GCC I am surprised that the latest works with ROOT, because that's acknowledged not to be the case by the ROOT team itself, so that's why we are in general a bit cautious when updating. For boost I agree an upper bound is probably less critical. @dberzano shall we discuss this in the next WP3?
