### ISSUE TITLE
Problem building ROOT

### ISSUE THREAD

**Issue by kouzinopoulos** [alisw/alidist#905]
I am trying to build a fresh installation of the O2 stack using AliBuild (and the master branch of AliDist):

`aliBuild --defaults o2-daq build O2`

However the compilation stops at the ROOT recipe, without a descriptive message of what went wrong/ what is missing. I am attaching sw/BUILD/ROOT-latest/log:

[log.txt](https://github.com/alisw/alidist/files/1411090/log.txt)

**Comment by matthiasrichter** [comment]
does aliDoctor report anything when you run it with the same default?

**Comment by sawenzel** [comment]
@kouzinopoulos , @ktf: I just had the same problem with a fresh installation on a new machine.
AliDoctor does not complain but then ROOT compilation fails at cmake stage because it does not find
things like `xml` or `ssl`. It seems to me that these are actual dependencies which should be expressed in the root recipe and reported by aliDoctor if not found.

@kouzinopoulos : In your case it suffices to install openssl-devel as a system package.

**Comment by ktf** [comment]
The problem is that both OpenSSL and XML are picked up from alien runtime, which is not there in the `o2-daq` default. I am thinking on how to solve this.

**Comment by sawenzel** [comment]
In my case it did not compile with the ordinary `o2` default. So the problem is wider than just `o2-daq`.

**Comment by ktf** [comment]
Can you have a look to https://github.com/alisw/alidist/pull/907 to see if it fixes the problem? Apparently we disable alien also in O2, for whatever reason.

**Comment by ktf** [comment]
Actually, let's close this and move the discussion in #907.
