### ISSUE TITLE
Document the branch structure and switch integration builds to proper branches

### ISSUE THREAD

**Issue by ktf** [alisw/alidist#95]
Since a few days a number of branches have appeared in alidist. We need to document what they are for  and eventually select which one to run in the integration builds (which are currently using master).

- [ ] Add documentation about branches nomeclature somewhere (alidist/README.md?)
- [ ] Fix ali-bot/config.yaml to pick up the proper branches.

**Comment by dberzano** [comment]
Indeed. Where do we document them?

**Comment by dberzano** [comment]
Just for reference (to be moved to a more appropriate location):

* **IB/v5-06/prod**: current stable environment for releases and daily builds
* **IB/v5-06/next**: updates to the current stable environment that will become prod at some point
* **IB/v5-05/prod**: all AliRoot v5-05 series currently used in production
* **IB/v5-05/legacy**: all AliRoot v5-05 series with some older components (notably GEANT3)

I'd say we create a wiki page on GitHub for that.

I'd keep master because it might be a convenient place to accept other people's pull requests for adjusting and testing them before porting them to production.

OK?

**Comment by ktf** [comment]
We should probably use both prod and next, so that prod is very quick given everything should have been build in next.

I'm not sure about keeping master. We can simply switch the repository default branch.
