### ISSUE TITLE
Build fails on lzma dependency

### ISSUE THREAD

**Issue by awegrzyn** [alisw/alidist#955]
**Configuration**
- macOS 10.13.1 
- clang-900.0.39.2

**Command**
```
aliBuild build Monitoring --defaults o2-daq
```
**Error**
```
./autogen.sh: line 17: autopoint: command not found
```

**Comment by awegrzyn** [comment]
@ktf @dberzano any progress on that? It fails on both of my macs

**Comment by dberzano** [comment]
Hi @awegrzyn, the problem is your Homebrew installation and it's unrelated to lzma. It seems that Homebrew does not link `autopoint` (from the `gettext` package I think) to `/usr/local/bin`. [There is a reason for that, apparently.](https://discourse.brew.sh/t/why-does-gettext-not-link-into-usr-local-bin/657)

The solution is to export the appropriate path in your shell rc (`~/.bashrc`, `~/.bash_profile`, `~/.profile`: whichever you use).

```bash
export PATH="/usr/local/opt/gettext/bin:$PATH"
```

Does this help?

**Comment by awegrzyn** [comment]
Hi @dberzano,
It works, thanks a lot. Maybe for the future `aliDoctor` could fail in such case.
